### ISSUE TITLE
Unable to create multiple container from an image

### ISSUE THREAD

**Issue by sanjaymp18** [sl1pm4t/terraform-provider-lxd#191] opened 2020-03-02 09:20 UTC
Using terraform, In modules main .tf is as below:

variable "name" {}
variable "cluster_name" {}
variable "image" {}
variable "cpu" { default = 1 }
variable "memory" { default = "1GB" }

resource "lxd_container" "conatiner" {
  config     = {}
  ephemeral  = false
  limits     = {
      "memory" = "128MB"
      "cpu" = 1
  }
  config = {
    "boot.autostart" = true
    "security.privileged" = true
  }
  device {
    name = "eth0"
    type = "nic"

    properties = {
      nictype = "bridged"
      parent  = "virbr0"
    }

  image      = "${lxd_cached_image.centos7.fingerprint}"
  wait_for_network = false
}
resource "lxd_cached_image" "centos7" {
 source_remote = "images"
source_image  = "centos/7"
copy_aliases  = true
}

using the above module creating 7 container, 2 container start getting created but later fails with the below error messages:

module.a.lxd_container.container[0]: Creating...
module.e.lxd_container.container[0]: Creating...
module.x.lxd_container.container[0]: Creating...
module.d.lxd_container.container[0]: Creating...
module.t.lxd_container.container[0]: Creating...
module.y.lxd_container.container[0]: Creating...
module.h.lxd_container.container[0]: Creating...
module.d.lxd_cached_image.centos7: Still creating... [40s elapsed]
module.y.lxd_cached_image.centos7: Still creating... [40s elapsed]
module.a.lxd_cached_image.centos7: Still creating... [40s elapsed]
module.x.lxd_cached_image.centos7: Still creating... [40s elapsed]
module.y.lxd_cached_image.centos7: Creation complete after 47s [id=cluster/7c5350a25b04b85b3e05aea6b1f83a95ab88]
module.d.lxd_container.container[0]: Creating...
module.d.lxd_container.container[0]: Still creating... [10s elapsed]
module.d.lxd_container.container[0]: Creation complete after 19s [id=testing-d-1]
Error: Failed remote image download: Image sync between nodes: UNIQUE constraint failed: images_nodes.image_id, images_nodes.node_id

  on modules/main.tf line 35, in resource "lxd_cached_image" "centos7":
  35: resource "lxd_cached_image" "centos7" {

Error: Failed remote image download: Image sync between nodes: UNIQUE constraint failed: images_nodes.image_id, images_nodes.node_id

  on modules/main.tf line 35, in resource "lxd_cached_image" "centos7":
  35: resource "lxd_cached_image" "centos7" {

Error: Failed remote image download: Image sync between nodes: UNIQUE constraint failed: images_nodes.image_id, images_nodes.node_id

  on modules/main.tf line 35, in resource "lxd_cached_image" "centos7":
  35: resource "lxd_cached_image" "centos7" {

Error: Failed remote image download: Image sync between nodes: UNIQUE constraint failed: images_nodes.image_id, images_nodes.node_id

  on modules/main.tf line 35, in resource "lxd_cached_image" "centos7":
  35: resource "lxd_cached_image" "centos7" {

Error: Failed remote image download: Image sync between nodes: UNIQUE constraint failed: images_nodes.image_id, images_nodes.node_id

  on modules/main.tf line 35, in resource "lxd_cached_image" "centos7":
  35: resource "lxd_cached_image" "centos7" {

Error: Failed remote image download: Image sync between nodes: UNIQUE constraint failed: images_nodes.image_id, images_nodes.node_id

  on modules/main.tf line 35, in resource "lxd_cached_image" "centos7":
  35: resource "lxd_cached_image" "centos7" {

Creating one container works fine.
Im not sure If im wrong with my lxd_cached_image configurations, i just want to create 7 container from the same image using terraform. 
How do i use an image in a container and create 7 containers.
 Kindly advice. Thanks

**Comment by jtopjian** [comment] 2020-03-03 03:44
@samp-git18 Using the simplified Terraform configuration below, this works for me:

```hcl
resource "lxd_container" "container" {
  count = 3

  name  = format("container%02d", count.index + 1)
  image = lxd_cached_image.centos7.fingerprint
}

resource "lxd_cached_image" "centos7" {
  source_remote = "images"
  source_image  = "centos/7"
  copy_aliases  = true
}
```

From the error messages you provided:

```
Error: Failed remote image download: Image sync between nodes: UNIQUE constraint failed: images_nodes.image_id, images_nodes.node_id
```

I'm wondering if this has something to do with LXD's clustering? If so, this provider is not compatible with LXD clustering (yet).

**Comment by samp-git18** [comment] 2020-03-03 06:17
@jtopjian  Yes your right, this is related to LXD clustering, the problem is every-time the main.tf is executed, the image is downloaded so due to clustering the images are shared so the 2nd attempt to downloading fails, so i couldn't think of a workaround for it, thus seeking advice on it.

**Comment by jtopjian** [comment] 2020-08-24 15:03
Since this is related to clustering, I'm going to close this issue since there are other issues already opened about the Clustering API. I can re-open this or discuss further if needed.

**Closed by jtopjian** 2020-08-24 15:03 UTC
