### ISSUE TITLE
Profiles always cause changes

### ISSUE THREAD

**Issue by mikescott** [sl1pm4t/terraform-provider-lxd#171] opened 2019-08-17 13:06 UTC
I have the following profile:

```terraform
resource "lxd_profile" "small" {
	name = "small"
	
    config = {
    	"limits.cpu" = 1
		"limits.memory" = "512MB"
		"boot.autostart" = true
    }
	
	device {
		name = "root"
		type = "disk"
		
		properties = {
			"pool" = "default"
			"path" = "/"
			"size" = "5GB"
			"limits.max" = "10MB"
		}
	}
	
	device {
		name = "eth0"
		type = "nic"
		
		properties = {
			"name" = "eth0"
			"nictype" = "bridged"
			"parent" = "lxdbr0"
			"limits.max" = "100Mbit"
		}
	}
}
```

Every time I run terraform plan or terraform apply it thinks there are changes, even though the profile hasn't been modified:

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

lxd_profile.small: Refreshing state... [id=small]
lxd_container.test1: Refreshing state... [id=test1]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # lxd_profile.small will be updated in-place
  ~ resource "lxd_profile" "small" {
        config = {
            "boot.autostart" = "true"
            "limits.cpu"     = "1"
            "limits.memory"  = "512MB"
        }
        id     = "small"
        name   = "small"

      + device {
          + name       = "eth0"
          + properties = {
              + "limits.max" = "100Mbit"
              + "name"       = "eth0"
              + "nictype"    = "bridged"
              + "parent"     = "lxdbr0"
            }
          + type       = "nic"
        }
      - device {
          - name       = "eth0" -> null
          - properties = {
              - "limits.max" = "100Mbit"
              - "nictype"    = "bridged"
              - "parent"     = "lxdbr0"
            } -> null
          - type       = "nic" -> null
        }
        device {
            name       = "root"
            properties = {
                "limits.max" = "10MB"
                "path"       = "/"
                "pool"       = "default"
                "size"       = "5GB"
            }
            type       = "disk"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by johnlane** [comment] 2019-12-22 09:55
I have the same problem but in my case it is a `lxd_container` that always changes. I have narrowed the cause down to devices having a `name` attribute, like this:
```
  device {
    name = "lab"
    type = "nic"
    properties = {
      name = "lab"
      nictype = "bridged"
      parent = "br_lab"
      hwaddr = "fa:de:be:ef:fa:ce"
    }
  }
```
It is the presence of `name` within the `properties` section that causes the problem for me. Just commenting out those entries allows `terraform plan` to report no changes. However, doing that doesn't help me because I need to specify named interfaces.

**Comment by jtopjian** [comment] 2019-12-27 19:42
I apologize for the late reply. It looks like the cause of the problem is the `name` argument in the `properties` block. Removing that does not cause the profile to be recreated.

I'm going to close this issue, but please let me know if you have any questions.

**Comment by johnlane** [comment] 2020-01-16 14:51
@jtopjian  what about when the `name` argument is needed? I need to use this to specify the name of the interface within the container (in my example above, it would define `/dev/lab` rather than `/dev/eth0`).

**Comment by jtopjian** [comment] 2020-01-16 15:12
I suggest piecing together the correct parameters on the command-line and then translating them into the Terraform arguments. This might uncover the correct combination to use.

**Comment by johnlane** [comment] 2020-01-17 09:18
Sorry not sure I follow. Can you give me an example of what you mean.
Are you saying that specifying `name` in the `properties` is incorrect and the behaviour we are seeing is not a bug but we are instead doing it wrong?

**Comment by jtopjian** [comment] 2020-01-17 15:23
Everything you do on the command line with the `lxc` tool is possible to do in Terraform. So one way of troubleshooting this issue is to figure out how to do it with the `lxc` command and then translate it to Terraform.

If you're able to do it with `lxc` but not Terraform then, yes, this is a bug and I'll re-open the issue.

**Comment by johnlane** [comment] 2020-01-18 19:54
Ok, as I understand it there is a "lxd device name" which is the one that appears in the Terraform `device` block. There's a second, optional, "kernel interface name" which is the one that goes in the `properties` block within the `device` block. It is the latter which translates into the interface name inside the container.

Take this example
```
resource "lxd_container" "test" {
  name = "test"
  image = "images:ubuntu/amd64"

  device {
    name = "foo"
    type = "nic"
    properties = {
      name = "bar"
      nictype = "bridged"
      parent = "br0"
    }
  }
}
```
(normally one would make the names the same; I'm differing them here to help illustrate)

I can do this on the host
```
$ lxc config device get test foo name
bar
```
I can change this on the host with
```
$ lxc config device set test foo name baz
```
And then, in the container
```
$ ip a
427: baz@if428: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state UP group default qlen 1000
```

When you do `terraform plan` you can see that the `name` existing property is not identified and the given value is therefore processed as a change.

      + device {
          + name       = "foo"
          + properties = {
              + "name"    = "baz"
              + "nictype" = "bridged"
              + "parent"  = "br0"
            }
          + type       = "nic"
        }
      - device {
          - name       = "foo" -> null
          - properties = {
              - "nictype" = "bridged"
              - "parent"  = "br0"
            } -> null
          - type       = "nic" -> null
        }

Interestingly, the `type` and device `name` also show up as differences. However, remove the `name` from the `properties` section and it works as expected - no changes reported when there aren't any.

**Comment by dgengtek** [comment] 2020-01-19 02:13
For reference the key `name` is a valid property for most network devices in lxd: https://github.com/lxc/lxd/blob/master/doc/instances.md#device-types

**Comment by jtopjian** [comment] 2020-01-19 04:10
@johnlane Thank you for the detailed explanation. This is indeed a bug and #184 should resolve this. I'll re-open this issue until #184 passes all tests.

**Comment by jtopjian** [comment] 2020-01-24 10:13
#184 has been merged and we'll have a new official release shortly. This issue should now be fixed for real, but do let me know if you're still having problems.

**Closed by jtopjian** 2020-01-24 10:13 UTC

**Comment by johnlane** [comment] 2020-01-29 19:28
@jtopjian, I just tested 1.3.0 and can confirm that the `name` key is now handled correctly. Thanks for the fix.

**Comment by sl1pm4t** [comment] 2020-01-29 19:58
Thanks @johnlane and thanks @jtopjian !
