### ISSUE TITLE
lxd_cached_image aliases not idempotent

### ISSUE THREAD

**Issue by nihr43** [sl1pm4t/terraform-provider-lxd#178] opened 2019-12-25 02:10 UTC
I'm trying to use an `alpine/stable` alias so that I have one place to represent base image upgrades across the entire infrastructure.  That works fine, but my alias is getting recreated on every `apply`.

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # lxd_cached_image.alpine will be created
  + resource "lxd_cached_image" "alpine" {
      + aliases        = [
          + "alpine/stable",
        ]
      + architecture   = (known after apply)
      + copied_aliases = (known after apply)
      + copy_aliases   = false
      + created_at     = (known after apply)
      + fingerprint    = (known after apply)
      + id             = (known after apply)
      + source_image   = "alpine/3.11"
      + source_remote  = "images"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

lxd_cached_image.alpine: Creating...

Error: Image alias already exists on destination: alpine/stable

  on images.tf line 1, in resource "lxd_cached_image" "alpine":
   1: resource "lxd_cached_image" "alpine" {
```

my `images.tf`:

```
resource "lxd_cached_image" "alpine" {
  source_remote = "images"
  source_image  = "alpine/3.11"
  aliases = ["alpine/stable"]
}
```

I've built at `b17e82d`
I'm using `Terraform v0.12.17`
My cluster is on `lxd 3.18`

**Comment by nihr43** [comment] 2019-12-25 03:40
I did `lxc image alias delete alpine/stable`, re-ran terraform a few times, and now i can't reproduce this.  though the above clearly shows a state which shouldn't be possible.

I'll keep an eye on this and see if i can get it to happen again.

**Comment by jtopjian** [comment] 2019-12-27 18:37
@nihr43 Thank you for the report. I'm unable to reproduce this issue with the Terraform configuration you provided, so I'm going to close this issue for now. I'm happy to re-open it if you run into this issue again.

**Closed by jtopjian** 2019-12-27 18:37 UTC
